[workspace]
authors = ["SrPeter128 <matthias.peter.kh@online.de>"]
channels = ["conda-forge"]
name = "myblink"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pip = ">=25.1.1,<26"
textual = ">=5.0.1,<6"
google-api-python-client = ">=2.177.0,<3"
google-auth-httplib2 = ">=0.2.0,<0.3"
google-auth-oauthlib = ">=1.2.2,<2"
python-dateutil = ">=2.9.0.post0,<3"
